steps:

  - label: ":lint-roller: Lint"
    command: "./.buildkite/scripts/lint.sh"

  - label: ":prettier: Prettier"
    command: "./.buildkite/scripts/prettier.sh"

  - block: ":rocket: Deploy to Dev?"
    if: "build.branch != 'main'"

  - label: "Deploy API"
    command: "./.buildkite/scripts/deploy-api.sh"
    cancel_on_build_failing: true

  - label: "Deploy UI"
    command: "./.buildkite/scripts/deploy-web.sh"
    cancel_on_build_failing: true