steps:
  - label: "Setup Environment Vars"
    command: "./.buildkite/scripts/set-env.sh"
    artifacts:
      - "./web/.env"
      
  - label: "Deploy API"
    command: "./.buildkite/scripts/deploy-api.sh"
    cancel_on_build_failing: true
    
  - label: "Deploy UI"
    command: "./.buildkite/scripts/deploy-ui.sh"
    cancel_on_build_failing: true