steps:

  - label: "Deploy API"
    command: "./.buildkite/scripts/deploy-api.sh"
    cancel_on_build_failing: true

  - block: ":rocket: Deploy to Dev?"

  - label: "Deploy UI"
    command: "./.buildkite/scripts/deploy-web.sh"
    cancel_on_build_failing: true