version: '3.8'

services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - CONTAINERIZED=true

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Password123
      POSTGRES_DB: mun
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
