services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.deploy
    ports:
      - "80:80"
    restart: always

  lint:
    build: 
      context: .
      dockerfile: Dockerfile.debug
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: yarn lint

  prettier:
    build:
      context: .
      dockerfile: Dockerfile.debug
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: yarn prettier --check ./**/*.tsx
      