# Runs the web app as a container. Used for prod environments

# Stage 1 - the build process
FROM node:18.12.0 as build-deps
ARG RUN_BUILD=true 

WORKDIR /usr/src/app
COPY package.json yarn.lock ./

RUN yarn install
COPY . ./

RUN yarn build

# Stage 2 - the production environment
FROM httpd:2.4

# Copy HTTPD.conf
COPY ./docker/httpd.conf /usr/local/apache2/conf

# Copy the built React app to the Nginx web root
COPY --from=build-deps /usr/src/app/build* /usr/local/apache2/htdocs

EXPOSE 80
